### ISSUE TITLE
Ask for details about synthetic data

### ISSUE THREAD

**Issue by han-shi** [ChiyuSONG/dynamics-of-instruction-tuning#1]
Hi, 

May I know the details about synthetic data generated by GPT-4? 
Like does the synthetic data share the same question as the human-curated question?
What is the prompting for these synthetic data?

Thanks!

**Comment by ChiyuSONG** [comment]
We utilized the synthetic data proposed by Peng et al. in their paper titled "Instruction Tuning with GPT-4" (https://arxiv.org/abs/2304.03277).
Its instruction pool is the same as Alpaca, which was generated using the "self-instruct" method. The responses were generated by GPT-4 and subsequently translated into Chinese using ChatGPT. The original dataset can be found [here](https://github.com/Instruction-Tuning-with-GPT-4/GPT-4-LLM#data-release).
